server:
  port: 8060

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: web-service

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:30000

    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka