server:
  port: 8060

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: web-service

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:30000

    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

  redis:
    port: 6379
    host: localhost

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: dondadondadondadondadondadondadondadondadondadonda  # 토큰 탈취를 막기 위해선 원래 숨겨야 한다.
  refresh-token-name: refresh-token
  access-token-name: access-token